# Jidoteki Admin tasks

- name: Create admin home directories
  file: >
    state=directory
    path={{ prefix }}{{ item }}
    owner=admin
    group=admin
    mode=1750
    recurse=no
  with_items:
    - "{{ admin_path }}/home"
    - "{{ admin_path }}/home/.ssh"
  tags:
    - admin

- name: Create admin directory structure
  file: >
    state=directory
    path={{ prefix }}{{ item }}
    owner=root
    group=root
    mode=0755
  with_items:
    - "{{ admin_path }}/bin"
    - "{{ admin_path }}/tmp"
    - "{{ admin_path }}/home/sftp"
  tags:
    - admin

- name: Create admin sftp uploads directory
  file: >
    state=directory
    path={{ prefix }}{{ item }}
    owner=sftpadmin
    group=admin
    mode=0770
    recurse=no
  with_items:
    - "{{ admin_path }}/home/sftp/uploads"
  tags:
    - admin

- name: Allow 'admin' to write to certain dirs
  file: >
    state=directory
    path={{ prefix }}{{ item }}
    owner=root
    group=admin
    mode=1775
  with_items:
    - "{{ admin_path }}/log"
    - "{{ admin_path }}/etc"
  tags:
    - admin

- name: Add SSH admin management scripts
  template: >
    src={{ item }}.j2
    dest="{{ prefix }}{{ admin_path }}/bin/{{ item }}"
    owner=root
    group=root
    mode=0755
  with_items:
    - update_certs.sh
    - update_debug.sh
    - update_license.sh
    - update_logs.sh
    - update_settings.sh
    - update_token.sh
    - update_vm.sh
  tags:
    - admin
    - updated

- name: Add SSH admin wrapper script
  template: >
    src=wrapper.sh.j2
    dest="{{ prefix }}{{ admin_path }}/bin/wrapper.sh"
    owner=root
    group=admin
    mode=0750
  tags:
    - admin
    - updated

- include: repos_debian.yml
- include: repos_centos.yml
