# Setup a local Debian/Ubuntu package repo

- name: Ensure local apt repo directory exists
  file: >
    path={{ local_repo_path }}/apt/debian/conf
    state=directory
    recurse=true
    owner=root
    group=root
    mode=0750
  tags:
    - debian
    - ubuntu

- name: Add options files for local apt repo
  copy: >
    src={{ item }}
    dest={{ local_repo_path }}/apt/debian/conf/{{ item }}
    owner=root
    group=root
    mode=0640
  with_items:
    - distributions
    - options
  tags:
    - debian
    - ubuntu

- name: Perform initial reprepro to create necessary files and directories
  shell: >
    chdir={{ local_repo_path }}/apt/debian
    reprepro -Vb . export
  tags:
   - debian
   - ubuntu
