# Jidoteki virtual appliance & live image administration
#
# Run the 'system' role first because it creates users needed in other roles.

- hosts: appliances
  gather_facts: false
  roles:
    - system
    - admin
    - api

- hosts: images
  gather_facts: false
  roles:
    - system
    - admin
