# Setup a local Debian/Ubuntu package repo

- name: Ensure local APT repo file is present
  template: >
    src=local.list.j2
    dest=/etc/apt/sources.list.d/local.list
    owner=root
    group=root
    mode=0640
  tags:
    - debian
    - ubuntu

- name: Ensure deps are installed
  apt: name={{ item }} state=latest
  with_items:
    - reprepro
    - curl
    - git-core
    - make
  tags:
   - debian
   - ubuntu
